const Data = [
    {
       "id":1,
       "photo":"https://toppng.com/public/uploads/preview/cool-avatar-transparent-image-cool-boy-avatar-11562893383qsirclznyw.png",
       "name":"Aftab",
       "age":19,
       "address":"bag-e-asra, upleta",
       "phone":"6354870886"
    },
    {
        "id":2,
        "photo":"https://tse2.mm.bing.net/th?id=OIP.pegfGc8sWHh2_RuwiuAknwHaHZ&pid=Api&P=0&h=180",
        "name":"Alfez",
        "age":18,
        "address":"jetpur",
        "phone":"6658419820"
     },
     {
        "id":3,
        "photo":"https://tse2.mm.bing.net/th?id=OIP.LftRMxkISZ37h5xsxfDCWQHaHa&pid=Api&P=0&h=180",
        "name":"Ayan",
        "age":19,
        "address":"jetpur",
        "phone":"5498210236"
     },
     {
        "id":4,
        "photo":"https://png.pngtree.com/png-clipart/20230102/original/pngtree-business-man-avatar-png-image_8855195.png",
        "name":"Irshad",
        "age":17,
        "address":"veraval",
        "phone":"5469326320"
     },
     {
        "id":5,
        "photo":"https://tse4.mm.bing.net/th?id=OIP.Dd3_Lw5gfn6QiV6RvJeYOgAAAA&pid=Api&P=0&h=180",
        "name":"Masoud",
        "age":19,
        "address":"surat",
        "phone":"4596371937"
     },
     {
        "id":6,
        "photo":"https://tse4.mm.bing.net/th?id=OIP.Dd3_Lw5gfn6QiV6RvJeYOgAAAA&pid=Api&P=0&h=180",
        "name":"Arshad",
        "age":18,
        "address":"veraval",
        "phone":"5693278264"
     },
        
]
export default Data